name: Code Check Site
'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@takasqr'

      - name: ci
        run: |
          cd site
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: lint
        run: |
          cd site
          npm run lint

      - name: typecheck
        run: |
          cd site
          npm run prepare
          npm run typecheck
          
      - name: test:unit
        run: |
          cd site
          npm run test:unit
  
      - name: testt:e2e
        run: |
          cd site
          npx playwright install
          npm run test:e2e

